import Head from "next/head";
import styles from "@/styles/Home.module.css";
import AccountButton from "../../Login/account-button";
import LoginButton from "../../Login/login-button";
import TourokuButton from "../../Login/touroku-button";
import LoginForm from "../../Login/loginform";
import Comment from "../../Login/comment";



export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main}`}>
                <div className={styles.divdiv}>
                    {/*--ログインフォーム--*/}
                    <LoginForm />

                    {/*--ログインボタン--*/}
                    <LoginButton />

                    {/*--新規登録ボタン--*/}
                    <TourokuButton />

                    {/*--文章--*/}
                    <Comment />

                    {/*--google--*/}
                    <AccountButton />

                </div>
            </main>
        </>
    );
};



