// テスト用
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <div style={{width: 1280, height: 832, position: 'relative', background: 'white'}}>
  <div style={{width: 499, height: 79, left: 390, top: 146, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div style={{width: 499, height: 79, left: 390, top: 252, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div style={{width: 197, height: 73, left: 390, top: 380, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div style={{width: 197, height: 73, left: 692, top: 380, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div style={{left: 416, top: 166, position: 'absolute', color: '#8E8585', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>メールアドレス</div>
  <div style={{left: 416, top: 273, position: 'absolute', color: '#8E8585', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>パスワード</div>
  <div style={{left: 727, top: 397, position: 'absolute', color: '#2B2828', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>ログイン</div>
  <div style={{left: 425, top: 397, position: 'absolute', color: '#2B2828', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>新規登録</div>
  <div style={{width: 499, height: 48, left: 390, top: 500, position: 'absolute', background: '#FF070C'}} />
  <div style={{width: 499, height: 48, left: 390, top: 595, position: 'absolute', background: '#70CBF2'}} />
  <div style={{width: 499, height: 48, left: 390, top: 690, position: 'absolute', background: 'black'}} />
  <div style={{left: 587, top: 505, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>Google</div>
  <div style={{left: 587, top: 600, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>Twitter</div>
  <div style={{left: 588, top: 694, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Inter', fontWeight: '400', wordWrap: 'break-word'}}>GitHub</div>
</div>
      </main>
    </>
  );
}
