import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
            <div style={{width: 2000, height: 1000, position: 'relative', background: 'white'}}>
                <div style={{
                    width: 499,
                    height: 79,
                    left: 700,
                    top: 146,
                    position: 'absolute',
                    background: 'white',
                    borderRadius: 24,
                    border: '1px black solid'
                }}>
                    <input type="text" style={{
                        width: '100%',
                        height: '100%',
                        border: 'none',
                        outline: 'none',
                        padding: '0 10px',
                        fontSize: '32px',
                        fontFamily: 'Inter',
                        fontWeight: '400',
                        color: '#8E8585',
                        borderRadius: '24px'
                    }} placeholder="email@.icloud.com"/>
                </div>
                <div style={{
                    width: 499,
                    height: 79,
                    left: 700,
                    top: 252,
                    position: 'absolute',
                    background: 'white',
                    borderRadius: 24,
                    border: '1px black solid'
                }}>
                    <input type="password" style={{
                        width: '100%',
                        height: '100%',
                        border: 'none',
                        outline: 'none',
                        padding: '0 10px',
                        fontSize: '32px',
                        fontFamily: 'Inter',
                        fontWeight: '400',
                        color: '#8E8585',
                        borderRadius: '24px'
                    }} placeholder="password"/>
                </div>
                <div style={{
                    width: 197,
                    height: 73,
                    left: 700,
                    top: 380,
                    position: 'absolute',
                    background: 'white',
                    borderRadius: 24,
                    border: '1px black solid'
                }}/>
                <div style={{
                    width: 197,
                    height: 73,
                    left: 1000,
                    top: 380,
                    position: 'absolute',
                    background: 'white',
                    borderRadius: 24,
                    border: '1px black solid'
                }}/>
                <div style={{
                    left: 1040,
                    top: 397,
                    position: 'absolute',
                    color: '#2B2828',
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: '400',
                    wordWrap: 'break-word'
                }}>ログイン
                </div>
                <div style={{
                    left: 734,
                    top: 397,
                    position: 'absolute',
                    color: '#2B2828',
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: '400',
                    wordWrap: 'break-word'
                }}>新規登録
                </div>
                <div style={{
                    width: 499,
                    height: 48,
                    left: 700,
                    top: 500,
                    position: 'absolute',
                    background: '#FF070C',
                    borderRadius: 24
                }}/>
                <div style={{
                    width: 499,
                    height: 48,
                    left: 700,
                    top: 595,
                    position: 'absolute',
                    background: '#70CBF2',
                    borderRadius: 24
                }}/>
                <div style={{
                    width: 499,
                    height: 48,
                    left: 700,
                    top: 690,
                    position: 'absolute',
                    background: 'black',
                    borderRadius: 24
                }}/>
                <div style={{
                    left: 900,
                    top: 500,
                    position: 'absolute',
                    color: 'white',
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: '400',
                    wordWrap: 'break-word'
                }}>Google
                </div>
                <div style={{
                    left: 900,
                    top: 595,
                    position: 'absolute',
                    color: 'white',
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: '400',
                    wordWrap: 'break-word'
                }}>Twitter
                </div>
                <div style={{
                    left: 900,
                    top: 689,
                    position: 'absolute',
                    color: 'white',
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: '400',
                    wordWrap: 'break-word'
                }}>GitHub
                </div>
            </div>
        </main>
    </>
  );
}
//sasa
